<ul class="form-list" id="payment_form_pagarme_checkout" style="display:none;">
    <input type="hidden" value="" name="payment[pagarme_checkout_token]" id="pagarme_checkout_token" class="required_entry" />
    <input type="hidden" value="" name="payment[pagarme_checkout_payment_method]" id="pagarme_checkout_payment_method" />
    <input type="hidden" value="" name="payment[pagarme_checkout_interest_rate]" id="pagarme_checkout_interest_rate" />

    <div style="display:none;" id="advice-required-entry-pagarme-checkout-hash" class="validation-advice">
        <?php echo __("Please click the button below<br />and complete the information."); ?>
    </div>

    <button id="pagarme-checkout-fill-info-button" class="button" type="button">
        <span>
            <span>
                <?php echo $this->getButtonText(); ?>
            </span>
        </span>
    </button>
</ul>

<script type="text/javascript" id="pagarme-checkout">

    var btnContinuePayment = $('payment-buttons-container').select('.button')[0]
    var pagarmeCheckoutRadio = document.getElementById('p_method_pagarme_checkout')

    function enableContinue () {
      btnContinuePayment.classList.remove('disabled')
      btnContinuePayment.disabled = false
    }

    function disableContinue () {
      btnContinuePayment.classList.add('disabled')
      btnContinuePayment.disabled = true
    }

    function pagarmeChecked () {
      if ($('pagarme_checkout_token').value === '') {
        return disableContinue()
      }
      enableContinue()
    }

    if (pagarmeCheckoutRadio.checked) {
      pagarmeChecked()
    }

    function togglePagarmeCheckoutButtonBehaviour (e) {
      if (e.target.tagName === 'INPUT') {
        if (e.target.id === 'p_method_pagarme_checkout') {
          return pagarmeChecked()
        }
        return enableContinue()
      }
    }

    $('checkout-payment-method-load').observe('click', togglePagarmeCheckoutButtonBehaviour)

    $("pagarme-checkout-fill-info-button").observe("click", function (event){
        var pagarmeCheckoutSettings = <?= json_encode($this->getCheckoutConfig()) ?>

        var checkoutPagarme = new PagarMeCheckout.Checkout({
            encryption_key : "<?= $this->getEncryptionKey() ?>",
            success: function (response) {
                enableContinue()
                $('pagarme-checkout-fill-info-button').remove()

                $('pagarme_checkout_token').value = response['token']
                $('pagarme_checkout_payment_method').value = response['payment_method']
                $('pagarme_checkout_interest_rate').value = pagarmeCheckoutSettings.interestRate
            }
        })

        checkoutPagarme.open(pagarmeCheckoutSettings)
    })
</script>
