<?php
    $transaction = \Mage::getModel('pagarme_v2_core/service_order')->getTransactionByOrderId($this->getOrder()->getId());
?>

<?php if ($transaction->getRateAmount() > 0): ?>
    <tr id="pagarme_v2_order_info_rate_amount">
        <td class="label">Rate Amount</td>
        <td><?= $this->displayPrices($transaction->getRateAmount(), $transaction->getRateAmount()) ?></td>
    </tr>
<?php endif; ?>
