<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php if(!empty($this->getBoletoUrl())): ?>
	<br />
	<button 
		onclick="window.open('<?php echo $this->getBoletoUrl() ?>')" 
		title="<?php echo $this->__('Click here to print your Boleto') ?>" 
		class="button" type="button">		
		<span><span><?php echo $this->__('Click here to print your Boleto') ?></span></span>		
	</button> 
<?php endif ?>